dynesty/priors.py

As a convenience, this adds some `Prior` objects that simplify writing the ``prior_transform`` function for selected prior distributions.

Add prospector-like Prior objects, for people to use if they want.

---

README.md
dynesty/__init__.py
dynesty/bounding.py
dynesty/dynamicsampler.py
dynesty/nestedsamplers.py
dynesty/plotting.py
dynesty/sampler.py
dynesty/sampling.py
dynesty/utils.py

Added an import exception for `builtins` and some basic information to the readme.

Installing

---

dynesty/sampling.py

Changed variable uhat to u_hat to avoid NameError during the RuntimeError call.

bug fix in sample_slice

---

dynesty/utils.py

Fixes minor bug in merge_results
I did try to add a dosctring, but I'm a little confused on exactly what samples_n acually is. Feel free to edit yourself or let me know what to fill in/otherwise change.

Closes #118

---

.travis.yml
dynesty/bounding.py
dynesty/dynamicsampler.py
dynesty/dynesty.py
dynesty/nestedsamplers.py
dynesty/plotting.py
dynesty/results.py
dynesty/sampler.py
dynesty/sampling.py
dynesty/utils.py

I identified some problematic variables. 
I added pyflakes to travis to detect such issues.

identified unused and missing variables

---

dynesty/sampler.py

Hi @joshspeagle, this PR adds an additional stopping condition that a certain number of posterior samples have been generated.
This is something we're looking at using in Bilby for gravitational-wave analysis where we want to get a decent number of samples in the shortest time possible.
It would be great if you think this is useful enough to merge into master.
This relies on the [Kish effective sample size](https://en.wikipedia.org/wiki/Effective_sample_size).

add number of effective posterior samples as a stopping condition

---

dynesty/dynesty.py

Added a "while True" loop to make sure there is at least one not -inf initial live pt.

Added initial live pts check.

---

dynesty/dynamicsampler.py
dynesty/results.py
dynesty/sampler.py

This pull request should remain backwards compatible, but it adds support for using [tqdm](https://github.com/tqdm/tqdm) for displaying progress if it's installed.
The benefit of this is that tqdm plays nice and doesn't swamp stderr. I did a simple test and this reduces the output from 1,330,315 characters written to stderr (over 6185 iterations) to 5,076 characters for a model that is fast to evaluate. I've found that in some simple test cases (especially in Jupyter notebooks) just the I/O of the progress bar can  dominate the computational load and this should help reduce that effect.
Feel free to ignore if its not something that you're interested in!

Adding support for tqdm for printing progress

---

dynesty/dynamicsampler.py

Added a few options (save_samples, resume)to the sample_initial function to help a pickled DynamicNestedSampler resume a run that was pickled while running the initial nested sampling.

Make the DynamicNestedSampler class work better with saving partial progress.

---

dynesty/bounding.py

add sanity check to avoid ellipsoids wandering off

---

dynesty/sampler.py
dynesty/sampling.py

Closes https://github.com/joshspeagle/dynesty/issues/202

make likelihood condition strictly increasing

---

dynesty/bounding.py
dynesty/nestedsamplers.py

Hi, 
This is an incomplete patch that would move away from volumes to logvolumes (in continuation of previous PR)
If there is a desire to have that, I can finish that. 
S

logvolume patch

---

py/dynesty/dynamicsampler.py

Hi 
I was struggling with a problem when I use rslice sampler
```
dsampler = dynesty.DynamicNestedSampler(
wrap_like,        prior_transf,
periodic=[2, 4],
ndim=11,        pool=pool,
queue_size=24,        sample='rslice',
use_pool={
'loglikelihood': True,
'evolve': False
})
dsampler.run_nested(dlogz_init=1,
nlive_init=500,
nlive_batch=500,
wt_kwargs={'pfrac': .9},
stop_kwargs={'pfrac': .9})
```
and I was getting all the time 
```
RuntimeError: Slice sampling appears to be stuck!
```
errors. 
The investigation showed that the problem is the following:
when sample_batch is called https://github.com/joshspeagle/dynesty/blob/eb72a2e02720cf7b4384728b995705e1d303cc38/py/dynesty/dynamicsampler.py#L943
it can have the logl interval that only contains a handful of (top) points from the base run. …

fix the bug in sample_batch when not enough live points exist

---

py/dynesty/bounding.py
py/dynesty/dynesty.py
py/dynesty/nestedsamplers.py
py/dynesty/utils.py
tests/test_egg.py
tests/test_ellipsoid.py
tests/test_gau.py
tests/test_pool.py
tests/test_saver.py

various ellipsoid speedups

---

tests/test_misc.py
tests/test_periodic.py
tests/test_printing.py

* Tests of maxcall
* Tests of printing
* Tests of periodic

Add more tests

---

py/dynesty/plotting.py

As also suggested in https://github.com/joshspeagle/dynesty/issues/212

Add option to set title quantiles of corner/traceplot

---

py/dynesty/bounding.py

Put an assertion that should never fail (I've seen warnings related to 
this error in the wild, better catch the issue early)

Put an assertion that should never fail

---

tests/test_dyn.py
tests/test_egg.py
tests/test_ellipsoid.py
tests/test_gau.py
tests/test_misc.py
tests/test_pathology.py
tests/test_printing.py
tests/test_saver.py

previously tests influenced each other.
Now each script has its own seed set up by pytest.fixture.

fix the problems with random seeds in tests.

---

py/dynesty/bounding.py
py/dynesty/dynamicsampler.py
tests/conftest.py
tests/test_dyn.py
tests/test_egg.py
tests/test_ellipsoid.py
tests/test_gau.py
tests/test_misc.py
tests/test_pathology.py
tests/test_periodic.py
tests/test_pool.py
tests/test_printing.py
tests/test_saver.py

This is a possible fix to #244 but the correctness needs to be verified.  (the tests do pass) 
Specifically I don't understand what determines the volume determination.
Also, somehow previously the logic was I think too complicated relying on base_ids.  I didn't see the reason for that so I just selected all the points above the lowest boundary from saved_run

Possible fix to #244

---

tests/test_misc.py

add a test with the loglike returning -inf

add a test with the loglike returning -inf

---

py/dynesty/nestedsamplers.py

Fix the remant of previous saved_* interface. 
The danger of naked try/except is clear.

The expected volume calculation was broken in recent commits

---

.github/workflows/test.yml
py/dynesty/bounding.py
py/dynesty/dynamicsampler.py
py/dynesty/nestedsamplers.py
py/dynesty/plotting.py
py/dynesty/sampler.py
py/dynesty/utils.py

Some pylint driven style improvements (remove unused variables, etc)

Linting fixes of dynamicsampler.py

---

py/dynesty/dynamicsampler.py

fix the summing of weights

---

py/dynesty/bounding.py

Avoid pinvh() as we already have the eigen decomposition.
Add comments

Tiny improvement to #264

---

py/dynesty/dynamicsampler.py
py/dynesty/sampling.py
tests/test_pathology.py

This is several commits.
One that revises the pointvol setting and only sets if there is one single point (as otherwise that can sometimes overinflate the ellipsoid)
I also remove the exception on slice sampling stuck (as discussed in #266)
Add a longer/more extended pathology test.

Fixes slice

---

py/dynesty/dynamicsampler.py

fix the problem when some weights are zero and the required number of points can't be selected

Fix the problem with zero weights

---

.github/workflows/test.yml
py/dynesty/nestedsamplers.py
py/dynesty/sampling.py
py/dynesty/utils.py

#218 incorrectly used np.random.directly instead of rstate
I've also added a test that will fail if it'll happen again.

remove  all the direct calls of np.random.*

---

tests/test_ncdim.py

the ncdim option is currently not tested at all. 
A trivial test that at least will hopefully prevent this code from breaking completely.

Add ncdim test

---

py/dynesty/bounding.py
py/dynesty/dynamicsampler.py
py/dynesty/nestedsamplers.py
py/dynesty/sampler.py
tests/test_gau.py

Volume branch

---

README.md
py/dynesty/bounding.py
py/dynesty/dynamicsampler.py
py/dynesty/dynesty.py
py/dynesty/nestedsamplers.py
py/dynesty/plotting.py
py/dynesty/results.py
py/dynesty/sampler.py
py/dynesty/sampling.py
py/dynesty/utils.py

add coverage/testing badges to the README page (it needs to be merged after #287 as it is branched from there)

Readme fix

---

tests/test_highdim.py
tests/test_misc.py
tests/utils.py

add rstate args to some of the tests (committed yesterday)

update testing infrastructure a bit

---

py/dynesty/dynamicsampler.py
py/dynesty/dynesty.py

refactor update_interval

---

docs/source/faq.rst
docs/source/overview.rst
docs/source/quickstart.rst
py/dynesty/plotting.py

Hello. I'm currently working through the dynesty documentation to learn how to use the package. I'm fixing typos as I go and will remove the work-in-progress status once my reading slows down or stops. Hope this helps – please let me know if you would like me to go about proposing documentation fixes some other way.

Fixed some typos in the documentation.

---

py/dynesty/bounding.py
py/dynesty/dynamicsampler.py
py/dynesty/dynesty.py
py/dynesty/nestedsamplers.py
py/dynesty/sampler.py
py/dynesty/sampling.py
py/dynesty/utils.py
tests/test_gau.py
tests/test_misc.py
tests/test_ncdim.py
tests/test_pool.py
tests/test_saver.py
tests/utils.py

update error message if trying to get bounding ellipse of a single point

---

tests/test_ellipsoid.py
tests/test_misc.py

Update a couple of easy tests to address #310 (test_exc and test_ellipsoids)
(branched out of master)

Test fixes2

---

.github/workflows/test.yml
py/dynesty/bounding.py
py/dynesty/plotting.py
py/dynesty/sampling.py
tests/test_gau.py
tests/test_highdim.py
tests/test_misc.py
tests/test_periodic.py
tests/test_printing.py
tests/test_saver.py
tests/test_volume.py

This addresses most of the #310 
Now there are just 
3 FAILED tests/test_dyn.py::test_dyn
in the run of 100 tests (x75 each) . 
I've also updated the boostrap logic
and added my test_code that allows diagnosing the quality of the ellipsoidal representation.

Test fixes3

---

.github/workflows/test.yml
py/dynesty/bounding.py
py/dynesty/nestedsamplers.py
py/dynesty/plotting.py
py/dynesty/sampler.py
py/dynesty/sampling.py
tests/test_gau.py
tests/test_highdim.py
tests/test_misc.py
tests/test_pathology.py
tests/test_periodic.py
tests/test_printing.py
tests/test_saver.py
tests/test_volume.py

Rewrite the random walk/stagger logic
Separate the uniform ball sampling from random walks.
Also update the slice sampling scaling following paper recommendations
This depends on #316 merged

Random walk rewrite

---

py/dynesty/sampling.py

Address the rstagger issue  in #320 
Before the recent changes the stagger factor was separate from scale, but in #319 I've combined them. That seems to break things, presumably because that breaks the Markov chain assumptions.

do not include the stagger factor in the scale calculation

---

py/dynesty/dynamicsampler.py
py/dynesty/dynesty.py
py/dynesty/nestedsamplers.py
py/dynesty/sampling.py
tests/test_egg.py
tests/test_gau.py

as discussed in https://github.com/joshspeagle/dynesty/issues/320

get rid of stagger sampler

---

py/dynesty/nestedsamplers.py

add reasoning for the scale update of rwalk

---

py/dynesty/sampling.py

This ensures that sample_rwalk does strict MH step 'walks' times. No adjustments or run till acceptance is attempted. It deals with #320 part 2. 
The tests pass as the test_highdim case. 
The potential issues with 1) Boudning ellipsoids with repeated points
2) Effect of repeats on sampling, point proposal 
3) Pathological likelihoods peaking next to the prior edge
4) Effects on merging dynamic runs
have not been investigated.

Attempt to fix broken rwalk

---

py/dynesty/dynamicsampler.py
py/dynesty/results.py
py/dynesty/utils.py
tests/test_misc.py

Here's a working preliminary implementation of the Results() that is more than just a dictionary. 
It still accepts the list of key values or a dictionary, but prevents manual updates, and adds some additional methods

New results object

---

py/dynesty/dynamicsampler.py
tests/test_reflect.py
tests/test_saver.py

put a warning if all likelihood values are the same. 

---

tests/test_misc.py

to ensure that the code is still tested/works

add a test that still exercises the n_mc option to stop_function

---

py/dynesty/utils.py

cleanup of merge_runs following the results() refactoring

Merge run cleanup

---

py/dynesty/results.py
py/dynesty/utils.py
tests/test_gau.py

Merge run fix

---

py/dynesty/utils.py
tests/test_gau.py

make resample_equal more numerically stable.

---

.github/workflows/test.yml
docs/source/dynamic.rst
docs/source/quickstart.rst

This is a beginning of doc fixes addressing all the recent changes. 
A major thing thing that needs editing is the uncertainties section.  (help needed)

Doc fixes 

---

py/dynesty/plotting.py

Hello,
I was facing a case where the final `logz` is high (around 2000). Everything works fine, but when I try to generate the `runplot()`, I get a NaN/Inf matplotlib error (see full error below). I tried using the `logplot=True` option, but because it does not use the log directly and still uses `np.exp(logz)` before scaling the axes in log, the result was the same.
I tried to use logz directly in the plot when `logplot=True` and it did fix the issue. The changes are similar to what is done in the [ultranest version of this function](https://github.com/JohannesBuchner/UltraNest/blob/master/ultranest/plot.py#L139).
Thank you!
----
Full error message (which is fixed by the PR when settings `logplot=True`):
```
/home/vandal/astro/dynesty/py/dynesty/plotting.py:201: RuntimeWarning: overflow …
```

Use logz directly when `logplot=True` to avoid overflows

---

CHANGELOG.md
py/dynesty/sampling.py
tests/test_sampling.py

Remerge the update_proposal commits to master branch from slice_expand

Slice expand

---

CHANGELOG.md
py/dynesty/dynamicsampler.py
py/dynesty/dynesty.py
py/dynesty/nestedsamplers.py
tests/test_misc.py

original patch by @ColmTalbot
rewritten test by @segasai

fix the code of custom samplers/updaters

---

docs/source/quickstart.rst

Commit b6c9d7cf488939e3a4bdab8c405ce298c8843482 moved the location of `sampling.py` and `nestedsamplers.py`. This PR adjusts sources to changes.

update source references
