- dynesty/utils.py
Fix for an edge case when using utils.merge_runs(). If you pass a list of results which has only a single baseline run in it, utils.merge_runs() dies. This will only happen when repeatedly merging runs after unraveling.
> add merge_runs fix

- setup.py
This makes sure that the setuptools version matches the package version (otherwise there can be problems when installing).
> Automatically acquire correct version number from `__init__`

- dynesty/plotting.py
Hey Josh,
I just fixed the TypeError from "numpy/core/fromnumeric.py", line 83, in _wrapreduction
TypeError: 'float' object cannot be interpreted as an index
by changing np.min() -> min() and np.max() -> max() in plotting.py.
Best,
Tansu
> Fixed the TypeError from "numpy/core/fromnumeric.py"

- dynesty/results.py
Here is an experiment to avoid scrambled terminal outputs when the terminal is not large enough.
https://stackoverflow.com/questions/566746/how-to-get-linux-console-window-width-in-python
On python2.7, one may want to install https://pypi.python.org/pypi/backports.shutil_get_terminal_size, but this code should gracefully continue if it is not available.
> Terminalout

- .travis.yml
- dynesty/dynamicsampler.py
- dynesty/sampler.py
- dynesty/utils.py
Hey Josh,
Numpy updated their latest Scipy version to 1.3.0, which requires python >3.5.  For some reason, under the current .travis.yml, even for the Python2.7 test, travis ends up installing Numpy 1.3.0, which makes it fail.  I edited out a few things that seemed unnecessary for travis (the miniconda lines), which fixes the automated tests.
Then, there was another bug.  Since version 1.0.0, Scipy deprecated scipy.misc.logsumexp(), which was finally removed in version 1.3.0 (the function is located in scipy.special.logsumexp since 0.19.0).  This causes dynesty to break for the latest Scipy version.
If you don't really care about the miniconda setup in the travis file, this PR fixes both of these issues (and passes the tests in both Python 2.7 and 3.6).
> Travis and Scipy fix

- dynesty/nestedsamplers.py
- dynesty/sampler.py
Hi,
We are trying to use Dynesty within the Bilby framework from LIGO, parallelized via MPI.
One issue we hit is that Python 3's built-in pickle module can't pickle "module" objects, and the "Sampler.rstate" object was the numpy.random module:
```
rstate: <class 'module'> <module 'numpy.random' from '/usr/local/lib/python3.7/site-packages/numpy/random/__init__.py'>
```
Now, it's entirely possible this is user error (we're using the simplest Gaussian example in bilby, so not setting rstate explicitly, etc).  It's also possible that this is a horrible idea of how to work around the issue... if one did want to override the rstate, this wouldn't get transmitted to Pool workers...
BUT, this (along with a small patch to bilby) does allow us to run in parallel using MPI!
> For pickling, remove 'rstate' from Sampler state

- dynesty/sampling.py
This is an initial suggestion for how to close #128. This lets the `u` wander outside the unit cube, then applies the logic to map it back in based on if the parameter is periodic or not. Periodic parameters get wrapped around the unit cube, 1.1 -> 0.1, while reflective (all non-periodic parameters) get reflected, e.g 1.1 -> 0.9. 
This is suggested as a "work in progress", I'd guess it needs implementing in all the other proposal methods so they have similar behaviours, but I thought I'd just put something initial in to see what you thought. This also makes some of the periodic checking code obsolete I think.
> Map the transformed u value in rwalk, either periodically, or reflect

- dynesty/bounding.py
- dynesty/nestedsamplers.py
See issue #121 .
For a simple gaussian likelihood on a unit cube::
```
scales = np.array([0.1, 0.001, 0.3])
def loglike(x):
return -0.5 * (((x - 0.5) / scales)**2).sum()
```
The speed-up from simple scaling is already a factor of 4.
The clustering that detects disjoint ball groups
helps scaling multimodal distributions.
The following likelihood:
```
scales = np.array([0.1, 0.001, 0.3])
mu1 = np.array([0.3, 0.2, 0.3])
mu2 = np.array([0.3, 0.4, 0.3])
def loglike(x):
l1 = -0.5 * (((x - mu1) / scales)**2).sum()
l2 = -0.5 * (((x - mu2) / scales)**2).sum()
return np.logaddexp(l1, l2)
```
Then sees another factor of 4 increase in efficiency.
The efficiency improvement will be arbitrarily high
when scales[1] is set to lower values.
Reference is https://arxiv.org/abs/1707.04476
> New implementation of mlfriends

- dynesty/sampling.py
In testing using bilby, we found that reflective boundaries can result in odd
behaviour at the boundary. We believe this is because the detailed balance of
the MCMC steps are no longer satisfied (multiple ways exist to get to the same
point). This removes the automated reflective boundaries for
non-periodic parameters (but retains periodic boundaries).
> Removes the automatic reflective boundaries

- setup.py
This is just a very minor change that will allow the Markdown "Project description" text to be rendered properly on the [PyPI project page](https://pypi.org/project/dynesty/). Obviously not a major issue, but it'll make things look slightly prettier for the next release :wink:
> Allow description markdown to be rendered on PyPI

- dynesty/sampler.py
If the logwt is too large, warning messages are produced by the
logsumexp terms. This stops that from occuring.
> Add an additional catch for cases where the logwt is close to infinity

- dynesty/sampling.py
- dynesty/utils.py
While the previous implementation worked. It was still possible to go so
far out of the unit cube that it didn't reflect properly (i.e. it was
mapped to a point on the other side, outside, of the unit cube). This
fixes that and ensures all points are mapped back in properly.
> Minor fix to the reflective implementation

- dynesty/dynamicsampler.py
- dynesty/sampler.py
Added in support for pools following #165, and added in a similar functionality for the `dynamicsampler`. That particular one might not work (I didn't test all cases), but since it wasn't even support originally and I'm not pushing it to PyPI yet I'm not too worried about it.
> getstate support

- dynesty/dynesty.py
- dynesty/nestedsamplers.py
- Users can pass `sampler=func` in `NestedSampler` where `func` is a
callable. It must have the same behaviour as the samplers defined in
dynesty.sampling.
- Also reduces a repeated definition of `_SAMPLING`
> Add option to pass user defined sample method

- dynesty/dynamicsampler.py
The __getstate__ method of the DynamicSampler wasn't actually being called as it had the wrong indentation and so was being considered a method of the __init__ method. I noticed this when trying to pickle DynamicSampler in the same way we do for the fixed live point samplers here. 
In combination with #188, this makes it a bit easier to save and resume progress.
> __getstate__ has wrong indentation for DynamicSampler

- .travis.yml
I also added 3.7 and 3.8 to the matrix since I assumed they are supported and should hence be tested.
> travis: update numpy to avoid mismatch between numpy and scipy

- dynesty/sampler.py
It looks like deleting `rstate`, `pool`  and `pool.map` was repeated [here ](https://github.com/joshspeagle/dynesty/blob/265bbe4bf6573704cea9ab4640ebf9e18edcae7f/dynesty/sampler.py#L161) and [here](https://github.com/joshspeagle/dynesty/blob/265bbe4bf6573704cea9ab4640ebf9e18edcae7f/dynesty/dynamicsampler.py#L469). I have added a simple try except statement in sampler.py to overcome this.
> fixed repeated removing while pickling sampler in sampler.py

- dynesty/utils.py
`np.int` is due to be deprecated in `numpy` (https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations)
> move np.int to int

- dynesty/dynamicsampler.py
- dynesty/dynesty.py
- dynesty/nestedsamplers.py
- dynesty/sampler.py
- dynesty/sampling.py
Hi @joshspeagle, this PR would add a new parameter `ncdim` to specify the number of parameters to do the clustering on. This is distinct from the `npdim` where the nuisance parameters are things that we don't expect to gain much information for, but we are still interested in being able to associate specific sample values with the measured parameters. Adding in the option to not cluster on these parameters makes ellipsoid construction faster/more reliable for the remaining parameters.
I've tested this with `ncdim` set and unset for all of the built-in sampling methods with the multi-ellipsoid sampler and it seems to work well. If you're interested in merging this, I'd be happy to do a quick test with the other samplers.
I've tried to follow the repository style, but let me know if there's …
> Specify clustering dimensions

- dynesty/bounding.py
Hi, 
This fixes https://github.com/joshspeagle/dynesty/issues/205 
The first patch actually addresses the root cause. 
When you scale the ellipsoid to contain all the points, you inadequately correct for the roundoff errors. 
See for example this where (similarly to bounding_ellipsoid()) function I determine the maximum norm 
to then scale the matrix such that the norm =1
The actual numbers deviate from 1 by up to 1e-5 for poorly conditioned matrices. 
```python
In [74]: delts=np.zeros(10000)
...: for i in range(len(delts)):
...:     ndim = 30
...:     df=30
...:     xs=np.random.normal(size=ndim)
...:     mat=scipy.stats.wishart(df=df,scale=np.ones(ndim)).rvs()
...:     val= xs@scipy.linalg.pinv(mat)@xs
...:     delts[i]=(xs@scipy.linalg.pinv(mat*val)@xs)
...: print …
```
> Ellipsoid fix

- dynesty/bounding.py
Trivial bug fix of one of previous commits a few days ago (caught by pylint)
> fix the variable naming issue in one of previous  commits

- .travis.yml
To ensure the most obvious errors are caught, I've added pylint to the travis testing.
> add pylint test to the test suite to catch trivial oversights

- dynesty/bounding.py
Another attempt to fix the problematic ellipsoids. Apparently it still didn't quite work (I had a problem that was consistently failing). 
The problem was that despite the fact that the covariance matrix was invertible and had positive eigen values, that still caused problem in the X^TAX normalization. The solution seems to be to start regularizing when condition number (ratio of eigen values) gets too high. I also moved the matrix regularization code in the special function. 
The cutoff values for the condition number of the matrix is still rather arbitrary, but it does solve my problem. 
I also directly observed the effect of that function kicking in. Basically it slows things down reducing the acceptance rate, but the fit goes through. I was thinking about adding a warning if that code …
> Regularization refactor

- py/dynesty/bounding.py
Hi, 
In my tests (I'm running fits of tens of thousands fits), I still managed to hit an occasional 'can't construct the ellipse bounding points' error, so I've lowered the threshold condition number when trying to improve the matrix to 1e12 (i.e. 1e6 axis ratio).  That seemed to have solved it for me. 
I hope that won't need more changing... 
S
> decrease the condition number of bounding ellipsoids

- tests/test_pathology.py
After changing the condition number in the matrix, the pathological test was running too long, so I speed it up a bit.  (changing the alpha)
> make a pathology less pathological to not run the test for 2hrs

- py/dynesty/dynamicsampler.py
- py/dynesty/dynesty.py
- py/dynesty/sampler.py
- py/dynesty/utils.py
- requirements.txt
- tests/test_pathology.py
- tests/test_saver.py
Hi,
following earlier discussion, 
I propose a test patch that implements optional saving of all likelihood evaluations (in an hdf5 file).
This is done by wrapping the likelihood function and occasionally dumping things into a file. 
If there are no objections, I can tie a few loose ends, i.e. ensure that the last few calls are not lost and adding some docs. 
(on a separate note, the use_pool dictionaries need a set of tests).
> Saving history of likelihood evaluations

- py/dynesty/bounding.py
trivial fix to avoid a warning if pointvol=0 (default)
> avoid warning if pointvol is 0

- py/dynesty/utils.py
Jitter_run is slow. (it takes 60% of time of test_dyn.py)
The patch makes trivial speedups
Before (cProfile on test_dyn.py)
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1664   79.624    0.048   97.583    0.059 utils.py:380(jitter_run)
```
After
```
1664   69.921    0.042   77.390    0.047 utils.py:380(jitter_run)
```
> speedup jitter_run

- py/dynesty/nestedsamplers.py
- py/dynesty/sampler.py
I've needed an urgent fix to #250 since my codes were crashing regularly, so here is a possible fix. 
I'm not sure that's the best possible fix, but I think it does the job.
Basically it adds optional arguments for propose_*() 
And for the propose_live it accepts a subset of indices. It also avoids the repeated loglikelihood calls. 
There is a bit of a leakage of abstractions, as an if statement is needed to provide different arguments to propose functions depending on which sampler method is used, but maybe it can be refactored later.
The patch include some white space changed due to yapfing of previously un-yapfed nestedsamplers.py
The patch is based on the #257 commit branch.
> Slice sampling fix 

- py/dynesty/dynesty.py
- py/dynesty/sampler.py
- py/dynesty/sampling.py
The current slice samplng code still gave me the problems like this
```
RuntimeError: Slice sampler has failed to find a valid point. Some useful output quantities:
u: [0.43015122 0.26744562 0.9999996  0.69852869 0.51943458 0.99987344]
u_left: [0.43015122 0.26744562 0.9999996  0.69852869 0.51943458 0.99987344]
u_right: [0.43015122 0.26744562 0.9999996  0.69852869 0.51943458 0.99987344]
u_hat: [-2.77555756e-16 -5.55111512e-17  0.00000000e+00 -1.11022302e-16
-1.11022302e-16  0.00000000e+00]
u_prop: [0.43015122 0.26744562 0.9999996  0.69852869 0.51943458 0.99987344]
loglstar: 549499.5271041454
logl_prop: 549499.5271040456
axis: [-5.43760729e-05 -1.47307934e-06  9.95810121e-08 -2.81106958e-06
-9.69705233e-06  8.84660396e-09]
axlen: 5.5325149793425564e-05
s: 0.0.
```
It turns out that the …
> refactor slice sampling

- py/dynesty/utils.py
I've started to take a stab at optimizing/understanding/clarifiying jitter_run.
I replaced all the numpy 'int' ,'bool' types by int, bool.
I also separated the code that detects decrease in number of live-points. (I verified that it produces the same results). 
I think I'd like to vectorize/clarify the jitter_run code, as currently it's a bit of a maze to me. It'd be also good to have some kind of references explaining the maths there...
> Refactor of jitter_run/utils

- .github/workflows/test.yml
- py/dynesty/utils.py
- tests/test_gau.py
- tests/test_pathology.py
This in development branch dealing with jitter_run() code. 
It's not yet finished. (it's fully working and could be committed but I plan to work further on this) 
It increases code coverage + add comments. 
And one thing I was trying to understand is the origin of this: 
```
lzterm = (math.exp(loglstar - logz_new) * loglstar +
math.exp(loglstar_new - logz_new) * loglstar_new)
h_new = (math.exp(cur_logdvol) * lzterm + math.exp(logz - logz_new) *
(h + logz) - logz_new)
```
from here https://github.com/segasai/dynesty/blob/e6b2c397859ff0a8aa44ca0586a0c7c4e0ad9f8d/py/dynesty/utils.py#L525
I couldn't find this in your paper and I was wondering if you can unpack/reason about this. 
It seems that lzterm is essentially L_i^2/Z_{i+1} + L_{i+1}^2/Z{i+1} 
I'm not sure I follow where this comes from. …
> Jitter speed/refactor

- py/dynesty/utils.py
a tiny fix to previous jitter changes discovered when running demo notebooks
> fix the logzerr calculation, (make sure it's an array)

- py/dynesty/bounding.py
- py/dynesty/dynamicsampler.py
- py/dynesty/dynesty.py
- py/dynesty/nestedsamplers.py
- tests/test_highdim.py
following #285
make the conditions stricter on hierarchical splits if the first split didn't work
also get rid of no-op vol_check option.
This partially recovers the losses of #284 (blue curve) as the deviations start to now happen at ndim=17
I'm not sure we'll be able to fully get it back, as the previous code used pointvol for this. In my mind there were cases where pointvol estimates were good and it was preventing excessive splitting but in some cases it was preventing splitting because of incorrect pointvols.
I also change the sampler to rslice in high dims.
> remove volume_check & update vol_dec for hierarchical splits

- py/dynesty/bounding.py
- py/dynesty/dynamicsampler.py
- py/dynesty/dynesty.py
- py/dynesty/nestedsamplers.py
- py/dynesty/plotting.py
- py/dynesty/results.py
- py/dynesty/sampler.py
- py/dynesty/sampling.py
- py/dynesty/utils.py
- tests/test_misc.py
Fix the overflow problem  that happens when trying to run on 128d gaussian 
```
In [1]: import test_highdim as T
In [7]: co= T.Config(np.random.RandomState(33),128)
In [9]: rstate=np.random.RandomState(33)
In [10]: co= T.Config(rstate,128)
In [11]: T.do_gaussian(co,'rslice','multi',rstate=rstate)
/home/skoposov/curwork/dynesty/py/dynesty/sampler.py:807: RuntimeWarning: overflow encountered in double_scalars
math.exp(loglstar_new - logz_new) * loglstar_new)
/home/skoposov/curwork/dynesty/py/dynesty/sampler.py:810: RuntimeWarning: invalid value encountered in double_scalars
dh = h_new - h
/home/skoposov/curwork/dynesty/py/dynesty/sampler.py:806: RuntimeWarning: overflow encountered in double_scalars
lzterm = (math.exp(loglstar - logz_new) * loglstar +
.... …
```
> Overflow fix

- py/dynesty/dynamicsampler.py
- py/dynesty/dynesty.py
- tests/test_dyn.py
- tests/test_highdim.py
- tests/test_misc.py
- tests/utils.py
Attempt to address #293 
1) I remove **kwargs from Nested and Dynamic samplers
2) add nlive parameter to Dynamic samplers that will be used as default nlive_init/nlive_batch if those are not specified.
> Kwargs fix

- py/dynesty/bounding.py
- py/dynesty/dynamicsampler.py
- py/dynesty/dynesty.py
- py/dynesty/nestedsamplers.py
- py/dynesty/plotting.py
- py/dynesty/results.py
- py/dynesty/sampler.py
- py/dynesty/sampling.py
- py/dynesty/utils.py
- tests/test_dyn.py
- tests/test_misc.py
- tests/test_pool.py
Although it could have been an option after 1.2, I thought addressing #307 is worthwhile as currently things are error-prone. 
now all the iterators return namedtuples and I think the code is cleaner. There is a fair bit of repeated code stuff and it may be refactored in the future, but it looks worth applying. 
I've also yanked the kl_divergence.
> Namedtuple iterator change

- .github/workflows/test.yml
- py/dynesty/dynamicsampler.py
- py/dynesty/nestedsamplers.py
- py/dynesty/sampler.py
- py/dynesty/sampling.py
- py/dynesty/utils.py
- pytest.ini
- tests/test_dyn.py
- tests/test_egg.py
- tests/test_gau.py
- tests/test_highdim.py
- tests/test_ncdim.py
- tests/test_pathology.py
- tests/test_periodic.py
- tests/test_pool.py
- tests/test_printing.py
- tests/test_saver.py
- tests/utils.py
get rid of dlog_batch internal variable
put in the dlogz=0.01 function parameter (currently not available from the outside yet)
Also prevent spurious warnings in the case we are sampling the 'top' part of the posterior. In that case I set the upper logl limit to be +inf. And if that's the case I'm not checking that logl is above loglmax. 
addresses #325
> Batch fixes

- py/dynesty/dynamicsampler.py
- py/dynesty/sampler.py
- tests/test_gau.py
Possible way of addressing #327 
add_batch now has a mode parameter
which can be weight (does what currently does)
manual (requires logl_bounds) 
or full
which does basically another full nested run.
I've also added 'auto' which currently is basically 'weight', but we can maybe change it.
> add different add_batch modes

- py/dynesty/bounding.py
- py/dynesty/dynamicsampler.py
- py/dynesty/sampling.py
- py/dynesty/utils.py
- tests/test_ellipsoid.py
- tests/test_highdim.py
Speeds up this by a factor of 6
```
import dynesty.bounding as db
import numpy as np
sig = np.identity(10)
cens = [(np.arange(10) == i).astype(int) for i in range(10)]
ells = db.MultiEllipsoid([db.Ellipsoid(xcen, sig) for xcen in cens])
x0 = np.zeros(10)
for i in range(1000000):
ells.within(x0)
```
> 6x speed up within() method of multiellipsoid

- py/dynesty/dynamicsampler.py
- py/dynesty/utils.py
- tests/test_misc.py
get rid of KL divergence based stop function
Use the n effective sample as a metric instead. The default configuration requires 10000  samples.
see #331 
This is based on #329 branch to avoid merging conflicts
> Stopping change

- docs/source/overview.rst
This is admittedly a very pedantic point but... "eponymous name" is sort of a pleonasm - "eponymous name" is sort of like "the thing that gives it its name's name"
> Delete "eponymous" in overview

- .github/workflows/test.yml
- TESTING.md
- requirements-dev.txt
While preparing #379, I hit a few errors where I didn't have the requisite packages for the test suite installed. This PR will document these requirements in `requirements-dev.txt`, and mention this in the `TESTING.md` documentation. It then adjusts the GitHub Actions workflow to use this file rather than re-listing the requirements manually in the workflow definition.
> Document requirements for test suite

- CHANGELOG.md
- py/dynesty/dynamicsampler.py
- py/dynesty/sampler.py
- tests/test_gau.py
- tests/test_misc.py
Currently the maximum number of effective samples `n_effective` in `Sampler.sample()` defaults to `np.inf`, implying no limit, yet `self.n_effective` is still computed (and then compared with `np.inf`), which takes time. The code already checks for `None`; this PR extends that check to also check that `n_effective` is not positive infinity before computing `n_effective`; this cuts the time spent in each call to `Sampler.sample()` by about half in the tests I've run.
> Do not compute n_effective when limit is infinite

- CHANGELOG.md
- py/dynesty/nestedsamplers.py
- py/dynesty/sampling.py
- tests/test_sampling.py
This is the PR and proposal to add a slice sampling doubling scheme from Neal 2003 (scheme number 4). 
The reason for this is this test for example. 
```python
from __future__ import (print_function, division)
import numpy as np
import dynesty
nlive = 1000
printing = True  # get_printing()
def loglike(x):
x1 = (x * 1e7)
x2 = x1.astype(int)
rng = np.random.default_rng(x2)
logl = rng.uniform() * 100 + 1e-9 * (x2 - x1).sum()
return logl
def prior_transform(x):
return x
def test_pathology():
ndim = 4
rstate = np.random.default_rng(56432)
SAMPLER = dynesty.DynamicNestedSampler
kw = dict()
sampler = SAMPLER(loglike,
prior_transform,
ndim,
nlive=nlive,
bound='multi',
sample='rslice',
rstate=rstate)
sampler.run_nested(print_progress=printing, **kw)
test_pathology()
```
When one runs it the code …
> Doubling steps with slice sampler

- CHANGELOG.md
- py/dynesty/nestedsamplers.py
- py/dynesty/sampler.py
- tests/test_pool.py
This is a change trying to address how tuning of proposal distributions is done. 
Previously only 'blob' returned from one every 'queue_size' was used to adjust the tuning params. 
With this change the update_PROPOSAL() are called every time to mostly accumulate statistics on number of acceptances and rejects and the actual update will happen still every queue_size. 
The advantages are 
* the scale adjustment can become much less noisy. I.e. if some parts of the posterior may require smaller scale. Currently that info may be missed, because only one of every queue_size results is analyzed 
* We can react by switching to doubling scheme for slice sampling even if just a single likelihood evaluation had an issue 
Disadvantages: 
* change in the update_() interface
* a little bit more CPU …
> Proposal update change 

- CHANGELOG.md
- py/dynesty/dynamicsampler.py
- py/dynesty/sampler.py
- tests/test_misc.py
While running the notebooks I stumbled up on this bug:
```
File "/tmp/qq.py", line 28, in <module>
dsampler2.run_nested(maxiter=50000, use_stop=False)
File "/home/skoposov/pyenv38/lib/python3.8/site-packages/dynesty/dynamicsampler.py", line 1810, in run_nested
passback = self.add_batch(
File "/home/skoposov/pyenv38/lib/python3.8/site-packages/dynesty/dynamicsampler.py", line 1973, in add_batch
for cur_results in self.sample_batch(nlive_new=nlive,
File "/home/skoposov/pyenv38/lib/python3.8/site-packages/dynesty/dynamicsampler.py", line 1392, in sample_batch
for it, results in enumerate(batch_sampler.add_live_points()):
File "/home/skoposov/pyenv38/lib/python3.8/site-packages/dynesty/sampler.py", line 407, in add_live_points
logvols = self.saved_run.D['logvol'][-1]
IndexError: list index …
```
> Bug with maxiter/maxcall and dynamic sampling

- .coveragerc
- .github/workflows/test.yml
- py/dynesty/bounding.py
- py/dynesty/pool.py
- tests/test_pool.py
To avoid forgetting this PR gets rid of cholesky transform when constructing ellipsoids. 
The reason is that since we are doing eigen transform anyway, we don't need to do cholesky on top. 
The transformation matrix from normal coordinates to ellipsoidal coordinates can be done with cholesky matrix L (where L L^T =C ) or through sqrt(L) V where (L is vector of eigen values and V are eigen vectors). 
This speeds up the tests somewhat. On my machine it seems to be ~ 10%. 
Also I relaxed one condition when checking whether the point belongs to multiple ellipsoids (in the hope of dealing with #396). 
Whether that is enough or not I don't know.
> Bounding update, getting rid of cholesky transform

- CHANGELOG.md
- py/dynesty/dynamicsampler.py
- py/dynesty/dynesty.py
- py/dynesty/nestedsamplers.py
- py/dynesty/sampler.py
- tests/test_misc.py
Fix #427
When the ellipsoid is being initialized as a bound, it's centred at zero and has unit variance, while it should be centred at 0.5 and have cov of ndim/4
> Fixes to bounding updates

- CHANGELOG.md
- py/dynesty/dynamicsampler.py
- py/dynesty/sampler.py
- py/dynesty/utils.py
- tests/test_misc.py
- tests/test_pool.py
- tests/test_resume.py
Addresses #438 
What remains to be done here is some kind of test that would prevent this bug from happening.
I.e. the test that would verify that after restoring with the pool, it's actually used. 
If I won't have an idea for the test, I'll be merging without.
> fix the resuming of dynamic nested sampler runs with the pool

- CHANGELOG.md
- py/dynesty/dynamicsampler.py
- py/dynesty/dynesty.py
- py/dynesty/nestedsamplers.py
- py/dynesty/sampler.py
- py/dynesty/sampling.py
This gets rid of npdim and produces a couple of deprecation warnings.
A couple of decisions I had to make -- I made sure to rename all the npdim= keywords in various classes (other than the top ones like NestedSampler and DynamicNestedSampler) to ndim=. The reason is that I prefer minimize the number of concepts/standard variable names throughout the code.
The consequence of that is that when we release this i don't quite know if restoring checkpoints from previous version will be possible. I don't think it is a big deal, but not everyone may agree.
This is followup from #456
> get rid of npdim

- CHANGELOG.md
- docs/source/quickstart.rst
- py/dynesty/dynesty.py
- py/dynesty/pool.py
- tests/test_pool.py
> Pool args fix

- py/dynesty/dynamicsampler.py
- py/dynesty/sampler.py
- py/dynesty/utils.py
Numpy 2.0 removes the array method `.ptp()` in favour of the function `np.ptp`. This replaces the handful of calls in the code.
> Replace x.ptp() with np.ptp(x)

- setup.py
#492
`pypandoc.convert` was deprecated and removed in pypandoc. The usage can be replaced with `pypandoc.convert_text` with no other changes.
> use pypandoc.convert_text method, fixes a potential error during setup
